#! /usr/bin/env python
# encoding: utf-8
# Anton Feldmann AT gmail dot com

#Copyright (c) 2012 anton.feldmann@gmail.com
#Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation  files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy,  modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the  Software is furnished to do so, subject to the following conditions:
#The above copyright notice and this permission notice shall be included in all copies or substantial portions of the  Software.

#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE  WARRANTIES# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR  COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

import os
import os.path
import sys
from waflib import Utils

platform = Utils.unversioned_sys_platform()
default_prefix='/usr/share/texmf/'

top='.'
out='build'

def options(opt):
	opt.add_option('--prefix', dest='prefix', default=default_prefix, help='installation prefix [default: %r]' % default_prefix)

def configure(conf):
	local_prefix=os.environ.get('TEXMFHOME')
	if not local_prefix:
		if platform == 'win32':
			print('Windows ??')
			# win32 preserves the case, but gettempdir does not
		else:
			local_prefix=conf.env.PREFIX

	default_prefix=local_prefix

def config_example(conf):
	conf.load('tex')

def build_example(bld):
	bld(features = 'tex',
	    type     = 'latex', # pdflatex or xelatex
	    source   = 'tex/example/diss/Diss.tex', # mandatory, the source
	    outs     = 'pdf', # 'pdf' or 'ps pdf'
	    prompt   = 1, # 0 for the batch mode
	    install_path = 'build/example/'
	    )



def build(bld):
	bld.install_files('${PREFIX}/tex/latex/wissdoc/', 'tex/latex/wissdoc/*.sty')
	bld.install_files('${PREFIX}/tex/latex/wissdoc/', 'tex/latex/wissdoc/*.cls')
	bld.install_files('${PREFIX}/tex/latex/biblatex/', 'tex/latex/biblatex/*.bst')

